import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import SideNav from "@/components/layout/sideNav";
import Header from "@/components/layout/header";
import { Toaster } from "@/components/ui/sonner"
import { TourProvider } from "@/components/layout/TourContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-[#F7F8FB]"}>
        <TourProvider>
          <div className="relative flex">
            <SideNav />
            <div className="flex-grow ml-24 z-[49]">
              <div className="sticky top-0 bg-[#F7F8FB] z-50">
                <Header />
              </div>
              {children}
              <Toaster position="top-center"/>
            </div>
          </div>
        </TourProvider>
      </body>
    </html>
  );
}